---
title: "911_Calls_for_Service_Seattle"
author: "Jason Jiang"
date: "210/10/17"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Import the data
```{r}
Calls_for_Service_Seattle <- read.csv("911_Calls_for_Service_Seattle.csv")
dim(Calls_for_Service_Seattle)
colnames(Calls_for_Service_Seattle)
dat <- Calls_for_Service_Seattle
Calls_for_Service_Seattle <- NULL
## Possibility 1: Take a sample of 5% of the rows
fraction = 0.05
set.seed(12345) ## Change this to your own number
sample_rows = sample(1:nrow(dat), floor(nrow(dat) * fraction))
dat_sample = dat[sample_rows,]
write.csv(dat_sample,"Seattle_Fraction_05.csv")
dat = dat_sample # overwrite the old dat
dat_sample = NULL # To clear RAM
gc() # garbage collection to further clear RAM
```
Take a look
```{r}
dim(dat)
colnames(dat)
```
count() is a better version of table()
```{r}
require(plyr)
des_count <- count(dat$Initial.Type.Description)
group_count <- count(dat$Initial.Type.Group)
subgroup_count <- count(dat$Initial.Type.Subgroup)
des_count[des_count$freq <= 100,]
group_count[group_count$freq <= 100,]
subgroup_count[subgroup_count$freq <= 100,]
head(dat)

```
Link with Google maps API
```{r}
library(RCurl)
library(RJSONIO)
library(plyr)
 
url <- function(address, return.call = "json", sensor = "false") {
 root <- "http://maps.google.com/maps/api/geocode/"
 u <- paste(root, return.call, "?address=", address, "&sensor=", sensor, sep = "")
 return(URLencode(u))
}
 
geoCode <- function(address,verbose=FALSE) {
 if(verbose) cat(address,"\n")
 u <- url(address)
 doc <- getURL(u)
 x <- fromJSON(doc,simplify = FALSE)
 if(x$status=="OK") {
 lat <- x$results[[1]]$geometry$location$lat
 lng <- x$results[[1]]$geometry$location$lng
 location_type <- x$results[[1]]$geometry$location_type
 formatted_address <- x$results[[1]]$formatted_address
 return(c(lat, lng, location_type, formatted_address))
 } else {
 return(c(NA,NA,NA, NA))
 }
}
 
##Test with a single address
address <- geoCode("The White House, Washington, DC")
address
#[1] "38.8976831"
#[2] "-77.0364972"
#[3] "APPROXIMATE"
#[4] "The White House, 1600 Pennsylvania Avenue Northwest, Washington, D.C., DC 20500, USA"
 
# Use plyr to getgeocoding for a vector
#address <- c("The White House, Washington, DC","The Capitol, Washington, DC")
#locations <- ldply(address, function(x) geoCode(x))
#names(locations) <- c("lat","lon","location_type", "forAddress")
 
#Location type, for more info check here: https://developers.google.com/maps/documentation/directions/
#"ROOFTOP" indicates that the returned result is a precise geocode for which we have location information accurate down to street address precision.
#RANGE_INTERPOLATED" indicates that the returned result reflects an approximation (usually on a road) interpolated between two precise points (such as intersections). Interpolated results are generally returned when rooftop geocodes are unavailable for a street address.
#GEOMETRIC_CENTER" indicates that the returned result is the geometric center of a result such as a polyline (for example, a street) or polygon (region).
```
Rgooglemaps
```{r}
library(RgoogleMaps)
lat = c(40.702147,40.718217,40.711614);
lon = c(-74.012318,-74.015794,-73.998284);
center = c(mean(lat), mean(lon));
zoom <- min(MaxZoom(range(lat), range(lon)));


Map <- GetMap(center=center, zoom=zoom,markers = paste0("&markers=color:blue|label:S|",                                                      
                                                          "40.702147,-74.015794&markers=color:green|label:G|40.711614,-74.012318&markers=",
                                                          "color:red|color:red|label:C|40.718217,-73.998284"), destfile = "MyTile1.png");





tmp <- PlotOnStaticMap(Map, lat = c(40.702147,40.711614,40.718217), 
                       lon = c(-74.015794,-74.012318,-73.998284), 
                       destfile = "MyTile1.png", cex=1.5,pch=20,                       
                       col=c('red', 'blue', 'green'), add=FALSE);


# Now let's add points with the points method:

PlotOnStaticMap(Map, lat = c(40.702147,40.711614,40.718217), 
                lon = c(-74.015794,-74.012318,-73.998284), 
                lwd=1.5,col=c('red', 'blue', 'green'),  points(x = 40.702148, y = NULL ), add=TRUE)
```



